import streamlit as st
from PIL import Image
import numpy as np
import your_caption_utils  # Your custom module for preprocessing and captioning

# Load models and tokenizer
cnn_encoder = your_caption_utils.load_encoder('cnn_encoder.h5')
rnn_decoder = your_caption_utils.load_decoder('rnn_decoder.h5')
tokenizer = your_caption_utils.load_tokenizer('tokenizer.pkl')

st.title("🖼️ Real-Time Image Caption Generator")
st.write("Upload an image and get a caption generated by a CNN + RNN model.")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file:
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded Image', use_column_width=True)

    # Save and preprocess
    img_path = f"temp_image.jpg"
    image.save(img_path)

    with st.spinner("Generating caption..."):
        features = your_caption_utils.extract_features(img_path, cnn_encoder)
        caption = your_caption_utils.generate_caption(features, rnn_decoder, tokenizer)

    st.success("Caption generated!")
    st.markdown(f"**Caption:** {caption}")

    